import mediaApiRepository, {
    consumeInventoryBundle,
    deleteFile,
    deletePrint,
    getFileList,
    getFiles,
    getInventoryItems,
    getPrint,
    getPrints,
    getUserInventoryItem,
    redeemReward,
    updateInventoryItem,
    uploadAssetImage,
    uploadAvatarGalleryImage,
    uploadAvatarImageLegacy,
    uploadEmoji,
    uploadGalleryImage,
    uploadPrint,
    uploadSticker,
    uploadVrcPlusIcon,
    uploadWorldImageLegacy
} from './mediaApiRepository.js';
import mediaFileRepository, {
    addScreenshotMetadata,
    copyImageToClipboard,
    cropAllPrints,
    cropPrintImage,
    deleteScreenshotMetadata,
    ensureScreenshotThumbnail,
    findScreenshotsBySearch,
    getExtraScreenshotData,
    getScreenshotFolderImages,
    getScreenshotFolderTree,
    getScreenshotLibraryStatus,
    getFileBase64,
    getLastScreenshot,
    getScreenshotMetadata,
    getUgcPhotoLocation,
    getVrchatPhotosLocation,
    getWorldScreenshots,
    invokeApp,
    openFileSelectorDialog,
    openFolderAndSelectItem,
    resizeImageToFitLimits,
    saveEmojiToFile,
    saveImageFile,
    savePrintToFile,
    saveStickerToFile,
    startScreenshotLibraryScan
} from './mediaFileRepository.js';

type MediaRepository = typeof mediaApiRepository & typeof mediaFileRepository;

const mediaRepository = Object.freeze({
    ...mediaApiRepository,
    ...mediaFileRepository
}) as MediaRepository;

export {
    getFiles,
    getFileList,
    deleteFile,
    uploadGalleryImage,
    uploadAvatarGalleryImage,
    uploadVrcPlusIcon,
    uploadEmoji,
    uploadSticker,
    uploadPrint,
    uploadAssetImage,
    getPrints,
    getPrint,
    deletePrint,
    getInventoryItems,
    getUserInventoryItem,
    updateInventoryItem,
    consumeInventoryBundle,
    redeemReward,
    resizeImageToFitLimits,
    uploadAvatarImageLegacy,
    uploadWorldImageLegacy,
    invokeApp,
    getFileBase64,
    getScreenshotMetadata,
    deleteScreenshotMetadata,
    addScreenshotMetadata,
    getExtraScreenshotData,
    findScreenshotsBySearch,
    startScreenshotLibraryScan,
    getScreenshotLibraryStatus,
    getScreenshotFolderTree,
    getScreenshotFolderImages,
    getWorldScreenshots,
    ensureScreenshotThumbnail,
    getLastScreenshot,
    getVrchatPhotosLocation,
    getUgcPhotoLocation,
    openFileSelectorDialog,
    openFolderAndSelectItem,
    copyImageToClipboard,
    saveImageFile,
    savePrintToFile,
    saveStickerToFile,
    saveEmojiToFile,
    cropPrintImage,
    cropAllPrints
};

export default mediaRepository;
