export function FriendsLocationsPageView({
    embedded,
    FriendsLocationsToolbar,
    activeSegment,
    segmentOptions,
    searchQuery,
    showSameInstance,
    cardScale,
    spacingScale,
    t,
    setActiveSegment,
    setSearchQuery,
    changeShowSameInstance,
    changeCardScalePreference,
    changeSpacingScalePreference,
    FriendsLocationsVirtualList,
    scrollRef,
    isLoading,
    isError,
    hasVisibleSections,
    rosterDetail,
    isFavoritesLoaded,
    positionedRows,
    visibleVirtualRows,
    cardGridGap,
    cardGridMinWidth,
    cardGridColumns,
    cardGridRowHeight,
    currentUserId,
    canUseFriendLocation,
    canSendInvite,
    canBoop,
    openSectionWorld,
    openSectionGroup,
    toggleFavoriteGroup,
    openFriendUser,
    openFriendWorld,
    openFriendGroup,
    launchFriendLocation,
    selfInviteFriendLocation,
    sendFriendInvite,
    requestFriendInvite,
    sendFriendBoop
}) {
    return (
        <div
            className={
                embedded
                    ? 'friend-view flex h-full min-h-0 flex-col p-3'
                    : 'friend-view x-container flex h-full min-h-0 flex-1 flex-col overflow-hidden p-4 pb-0'
            }
        >
            <FriendsLocationsToolbar
                activeSegment={activeSegment}
                segmentOptions={segmentOptions}
                searchQuery={searchQuery}
                showSameInstance={showSameInstance}
                cardScale={cardScale}
                spacingScale={spacingScale}
                t={t}
                onActiveSegmentChange={setActiveSegment}
                onSearchQueryChange={setSearchQuery}
                onShowSameInstanceChange={changeShowSameInstance}
                onCardScaleChange={changeCardScalePreference}
                onSpacingScaleChange={changeSpacingScalePreference}
            />

            <FriendsLocationsVirtualList
                scrollRef={scrollRef}
                isLoading={isLoading}
                isError={isError}
                hasVisibleSections={hasVisibleSections}
                rosterDetail={rosterDetail}
                activeSegment={activeSegment}
                isFavoritesLoaded={isFavoritesLoaded}
                positionedRows={positionedRows}
                visibleVirtualRows={visibleVirtualRows}
                cardGridGap={cardGridGap}
                cardGridMinWidth={cardGridMinWidth}
                cardGridColumns={cardGridColumns}
                cardGridRowHeight={cardGridRowHeight}
                currentUserId={currentUserId}
                cardScale={cardScale}
                spacingScale={spacingScale}
                canUseFriendLocation={canUseFriendLocation}
                canSendInvite={canSendInvite}
                canBoop={canBoop}
                t={t}
                onOpenSectionWorld={openSectionWorld}
                onOpenSectionGroup={openSectionGroup}
                onToggleFavoriteGroup={toggleFavoriteGroup}
                onOpenFriendUser={openFriendUser}
                onOpenFriendWorld={openFriendWorld}
                onOpenFriendGroup={openFriendGroup}
                onLaunchFriendLocation={launchFriendLocation}
                onSelfInviteFriendLocation={selfInviteFriendLocation}
                onSendFriendInvite={sendFriendInvite}
                onRequestFriendInvite={requestFriendInvite}
                onSendFriendBoop={sendFriendBoop}
            />
        </div>
    );
}
