import type { EntityRecord } from './shared';

export type UnityPackageRecord = EntityRecord & {
    assetUrl?: string;
    assetVersion?: number;
    created_at?: string;
    id?: string;
    platform?: string;
    performanceRating?: string;
    impostorizerVersion?: string;
    scanStatus?: string;
    unitySortNumber?: number;
    unityVersion?: string;
    variant?: string;
    worldSignature?: string;
};

export type AvatarStatsRecord = EntityRecord & {
    animatorCount?: number;
    audioSourceCount?: number;
    blendShapeCount?: number;
    boneCount?: number;
    bounds?: number[];
    cameraCount?: number;
    clothCount?: number;
    constraintCount?: number;
    constraintDepth?: number;
    contactCount?: number;
    lightCount?: number;
    lineRendererCount?: number;
    materialCount?: number;
    materialSlotsUsed?: number;
    meshCount?: number;
    meshParticleMaxPolygons?: number;
    particleCollisionEnabled?: boolean;
    particleSystemCount?: number;
    particleTrailsEnabled?: boolean;
    physBoneColliderCount?: number;
    physBoneCollisionCheckCount?: number;
    physBoneComponentCount?: number;
    physBoneTransformCount?: number;
    physicsColliders?: number;
    physicsRigidbodies?: number;
    raycastCount?: number;
    skinnedMeshCount?: number;
    totalClothVertices?: number;
    totalMaxParticles?: number;
    totalPolygons?: number;
    totalTextureUsage?: number;
    totalVertices?: number;
    trailRendererCount?: number;
    writeDefaultsUsed?: boolean;
};

export type FileAnalysisRecord = {
    avatarStats?: AvatarStatsRecord;
    performanceRating?: string;
    _fileSize?: string;
    _totalTextureUsage?: string;
    _uncompressedSize?: string;
};

export type PlatformFileAnalysis = Record<string, FileAnalysisRecord>;

export type WorldProfileRecord = EntityRecord & {
    id: string;
    name: string;
    description: string;
    authorId: string;
    authorName: string;
    capacity: number;
    created_at?: string;
    createdAt: string;
    defaultContentSettings?: EntityRecord;
    disabledPropAbilities?: string[];
    favorites: number;
    featured?: boolean;
    fileAnalysis?: PlatformFileAnalysis;
    hasPersistData?: boolean;
    heat: number;
    imageUrl: string;
    instances?: unknown[];
    isLabs: boolean;
    labsPublicationDate?: string | null;
    occupants: number;
    organization?: string;
    platforms: string[];
    popularity: number;
    previewYoutubeId?: string | null;
    privateOccupants?: number;
    publicOccupants?: number;
    publicationDate: string | null;
    recommendedCapacity: number;
    releaseStatus: string;
    slimInstances?: unknown[];
    tags: string[];
    thumbnailImageUrl: string;
    udonProducts?: unknown[];
    unityPackages?: UnityPackageRecord[];
    updated_at?: string;
    updatedAt: string;
    urlList?: string[];
    version?: number;
    visits: number;
    $cacheLocked?: boolean;
    $cachePath?: string;
    $cacheSize?: string;
    $isCached?: boolean;
};
