[package]
name = "vrcx-0-local-server"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Shared local server primitives"

[dependencies]
base64 = { workspace = true }
constant_time_eq = "0.6"
getrandom = "0.4"
http = "1"
socket2 = "0.6"
tokio = { workspace = true, features = ["macros", "net", "rt"] }
