mod api;
mod backend;
mod bootstrap;
mod domain;
mod error;
mod state;

use tauri::tray::{MouseButton, MouseButtonState, TrayIconEvent};
use tauri::Manager;
use tauri::WindowEvent;

use state::AppState;

pub fn run() {
    bootstrap::init_error_logging();
    bootstrap::init_tls_crypto_provider();
    bootstrap::apply_linux_webkit_workaround();

    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            bootstrap::show_main_window(app);
        }))
        .register_asynchronous_uri_scheme_protocol("vrcx-0-img", |_ctx, request, responder| {
            tauri::async_runtime::spawn_blocking(move || {
                responder.respond(bootstrap::screenshot_protocol_response(request));
            });
        })
        .register_asynchronous_uri_scheme_protocol("vrcx-0-thumb", |_ctx, request, responder| {
            tauri::async_runtime::spawn_blocking(move || {
                responder.respond(bootstrap::screenshot_thumbnail_protocol_response(request));
            });
        })
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(
            tauri_plugin_updater::Builder::new()
                .pubkey(bootstrap::updater_public_key())
                .build(),
        )
        .plugin(
            tauri_plugin_window_state::Builder::new()
                .with_state_flags(
                    tauri_plugin_window_state::StateFlags::SIZE
                        | tauri_plugin_window_state::StateFlags::POSITION
                        | tauri_plugin_window_state::StateFlags::MAXIMIZED
                        | tauri_plugin_window_state::StateFlags::FULLSCREEN,
                )
                .build(),
        );

    #[cfg(target_os = "windows")]
    let builder = builder.plugin(tauri_plugin_autostart::init(
        tauri_plugin_autostart::MacosLauncher::LaunchAgent,
        Some(vec!["--autostart"]),
    ));

    #[cfg(target_os = "linux")]
    let builder = builder.plugin(tauri_plugin_autostart::init(
        tauri_plugin_autostart::MacosLauncher::LaunchAgent,
        Some(vec!["--autostart"]),
    ));

    builder
        .on_window_event(|window, event| {
            if window.label() != "main" {
                return;
            }

            if let WindowEvent::CloseRequested { api, .. } = event {
                let state = window.state::<AppState>();
                if state.storage.get("VRCX_CloseToTray").as_deref() == Some("true") {
                    api.prevent_close();
                    let _ = window.hide();
                    let _ = window.set_skip_taskbar(true);
                }
            }
        })
        .on_tray_icon_event(|app, event| match event {
            TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            }
            | TrayIconEvent::DoubleClick {
                button: MouseButton::Left,
                ..
            } => {
                bootstrap::show_main_window(app);
            }
            _ => {}
        })
        .setup(bootstrap::setup_app)
        .on_menu_event(|app, event| {
            if event.id().0 == "tray-exit" {
                app.exit(0);
            }
        })
        .invoke_handler(tauri::generate_handler![
            api::storage::storage__get,
            api::storage::storage__set,
            api::storage::storage__flush,
            api::storage::storage__remove,
            api::storage::storage__get_all,
            api::database::sqlite__begin_upgrade,
            api::database::sqlite__commit_upgrade,
            api::database::sqlite__fail_upgrade,
            api::database::sqlite__get_failed_upgrade,
            api::web::web__clear_cookies,
            api::web::web__get_cookies,
            api::web::web__set_cookies,
            api::app::error_log::app__append_error_log,
            api::asset_bundle::asset_bundle__get_vrchat_cache_full_location,
            api::asset_bundle::asset_bundle__check_vrchat_cache,
            api::asset_bundle::asset_bundle__delete_cache,
            api::asset_bundle::asset_bundle__delete_all_cache,
            api::asset_bundle::asset_bundle__sweep_cache,
            api::asset_bundle::asset_bundle__get_cache_size,
            api::log_watcher::log_watcher__get,
            api::log_watcher::log_watcher__get_current_location,
            api::log_watcher::log_watcher__set_date_till,
            api::log_watcher::log_watcher__reset,
            api::log_watcher::log_watcher__vrc_closed_gracefully,
            api::app::game::app__check_game_running,
            api::app::game::app__is_game_running,
            api::app::game::app__is_steamvr_running,
            api::app::game::app__set_game_client_runtime_state,
            api::app::game::app__quit_game,
            api::app::game::app__start_game,
            api::app::game::app__start_game_from_path,
            api::app::realtime::app__start_realtime_transport,
            api::app::realtime::app__sync_realtime_friend_snapshot,
            api::app::realtime::app__sync_realtime_current_user_snapshot,
            api::app::realtime::app__expire_realtime_notification,
            api::app::realtime::app__stop_realtime_transport,
            api::app::local_data::app__config_set_values,
            api::app::local_data::app__config_list_values,
            api::app::local_data::app__config_remove_value,
            api::app::local_data::app__user_tables_ensure,
            api::app::local_data::app__database_maintenance_run,
            api::app::local_data::app__database_maintenance_table_sizes_get,
            api::app::local_data::app__database_maintenance_max_friend_log_number_get,
            api::app::local_data::app__database_maintenance_broken_leave_entries_get,
            api::app::local_data::app__database_maintenance_broken_game_log_display_names_get,
            api::app::local_data::app__avatar_cache_upsert,
            api::app::local_data::app__avatar_cache_get,
            api::app::local_data::app__avatar_cache_list,
            api::app::local_data::app__avatar_cache_remove,
            api::app::local_data::app__avatar_history_add,
            api::app::local_data::app__avatar_history_list,
            api::app::local_data::app__avatar_time_spent_add,
            api::app::local_data::app__avatar_time_spent_get,
            api::app::local_data::app__avatar_time_spent_list,
            api::app::local_data::app__avatar_history_clear,
            api::app::local_data::app__avatar_tag_add,
            api::app::local_data::app__avatar_tags_get,
            api::app::local_data::app__avatar_tags_list,
            api::app::local_data::app__avatar_tags_distinct,
            api::app::local_data::app__avatar_tag_update_color,
            api::app::local_data::app__avatar_tag_remove,
            api::app::local_data::app__avatar_tags_remove_all,
            api::app::local_data::app__avatar_tags_replace,
            api::app::local_data::app__avatar_tags_patch,
            api::app::local_data::app__feed_add_entry,
            api::app::local_data::app__feed_avatar_purge,
            api::app::local_data::app__feed_live_rows_merge,
            api::app::local_data::app__feed_read_model_query,
            api::app::local_data::app__feed_rows_query,
            api::app::local_data::app__game_log_entries_add,
            api::app::local_data::app__game_log_instance_delete_by_location,
            api::app::local_data::app__game_log_instance_delete,
            api::app::local_data::app__game_log_entry_delete,
            api::app::local_data::app__game_log_query,
            api::app::local_data::app__player_list_location_get,
            api::app::local_data::app__player_list_latest_location_get,
            api::app::local_data::app__player_list_join_leave_rows,
            api::app::local_data::app__instance_activity_dates_get,
            api::app::local_data::app__instance_activity_rows_get,
            api::app::local_data::app__world_summaries_get,
            api::app::local_data::app__activity_self_source_slice,
            api::app::local_data::app__activity_self_source_after,
            api::app::local_data::app__activity_friend_presence_slice,
            api::app::local_data::app__activity_friend_presence_after,
            api::app::local_data::app__activity_self_sessions_refresh,
            api::app::local_data::app__activity_sync_state_get,
            api::app::local_data::app__activity_sync_state_upsert,
            api::app::local_data::app__activity_sessions_get,
            api::app::local_data::app__activity_sessions_replace,
            api::app::local_data::app__activity_sessions_append,
            api::app::local_data::app__activity_bucket_cache_get,
            api::app::local_data::app__activity_bucket_cache_upsert,
            api::app::local_data::app__mutual_graph_tables_ensure,
            api::app::local_data::app__mutual_graph_snapshot_get,
            api::app::local_data::app__mutual_graph_snapshot_save,
            api::app::local_data::app__mutual_graph_friend_update,
            api::app::local_data::app__mutual_graph_meta_upsert,
            api::app::local_data::app__mutual_graph_meta_bulk_upsert,
            api::app::local_data::app__world_cache_upsert,
            api::app::local_data::app__world_cache_list,
            api::app::local_data::app__world_cache_get,
            api::app::local_data::app__world_cache_remove,
            api::app::local_data::app__favorite_list,
            api::app::local_data::app__favorite_add,
            api::app::local_data::app__favorite_remove,
            api::app::local_data::app__favorite_group_rename,
            api::app::local_data::app__favorite_group_delete,
            api::app::local_data::app__memo_get_user,
            api::app::local_data::app__memo_list_users,
            api::app::local_data::app__memo_list_user_notes,
            api::app::local_data::app__memo_get_world,
            api::app::local_data::app__memo_get_avatar,
            api::app::local_data::app__memo_save_user,
            api::app::local_data::app__memo_save_world,
            api::app::local_data::app__memo_save_avatar,
            api::app::local_data::app__friend_log_current_list,
            api::app::local_data::app__friend_log_history_query,
            api::app::local_data::app__friend_log_replace_current,
            api::app::local_data::app__friend_log_delete_current_array,
            api::app::local_data::app__friend_log_upsert_current,
            api::app::local_data::app__friend_log_delete_current,
            api::app::local_data::app__friend_log_history_add,
            api::app::local_data::app__friend_log_history_delete,
            api::app::local_data::app__notification_rows_query,
            api::app::local_data::app__notification_list_query,
            api::app::local_data::app__notification_add_v1,
            api::app::local_data::app__notification_add_v2,
            api::app::local_data::app__notification_v2_expire,
            api::app::local_data::app__notification_v2_mark_seen,
            api::app::local_data::app__notification_update_expired,
            api::app::local_data::app__notification_delete,
            api::app::local_data::app__notification_expire,
            api::app::local_data::app__notification_mark_seen_local_bulk,
            api::app::local_data::app__local_moderation_list,
            api::app::local_data::app__local_moderation_get,
            api::app::host_capabilities::app__get_host_capabilities,
            api::app::paths::app__current_culture,
            api::app::paths::app__current_language,
            api::app::backend_runtime::app__backend_app_snapshot_get,
            api::app::backend_runtime::app__backend_background_frontend_due_jobs_get,
            api::app::backend_runtime::app__backend_background_frontend_job_defer,
            api::app::backend_runtime::app__backend_background_frontend_schedules_reset,
            api::app::backend_runtime::app__backend_background_job_record,
            api::app::backend_runtime::app__backend_background_jobs_snapshot_get,
            api::app::backend_runtime::app__backend_diagnostics_get,
            api::app::backend_runtime::app__backend_runtime_snapshot_get,
            api::app::backend_runtime::app__backend_sync_snapshot_get,
            api::app::backend_external::service::app__backend_external_avatar_search_get,
            api::app::backend_external::service::app__backend_external_github_releases_get,
            api::app::backend_external::service::app__backend_external_image_data_url_get,
            api::app::backend_external::service::app__backend_external_translation_request,
            api::app::backend_external::service::app__backend_external_vrc_status_json_get,
            api::app::backend_external::service::app__backend_external_youtube_video_metadata_get,
            api::app::backend_auth::app__backend_auth_scope_get,
            api::app::backend_auth::app__backend_auth_scope_set,
            api::app::backend_vrchat_auth::service::app__backend_auth_config_get,
            api::app::backend_vrchat_auth::service::app__backend_auth_current_user_get,
            api::app::backend_vrchat_auth::service::app__backend_auth_email_otp_verify,
            api::app::backend_vrchat_auth::service::app__backend_auth_file_analysis_get,
            api::app::backend_vrchat_auth::service::app__backend_auth_login_success_record,
            api::app::backend_vrchat_auth::service::app__backend_auth_login_basic,
            api::app::backend_vrchat_auth::service::app__backend_auth_logout_record,
            api::app::backend_vrchat_auth::service::app__backend_auth_otp_verify,
            api::app::backend_vrchat_auth::service::app__backend_auth_saved_credential_delete,
            api::app::backend_vrchat_auth::service::app__backend_auth_saved_snapshot_get,
            api::app::backend_vrchat_auth::service::app__backend_auth_session_get,
            api::app::backend_vrchat_auth::service::app__backend_auth_totp_verify,
            api::app::backend_vrchat_auth::service::app__backend_auth_visits_get,
            api::app::backend_avatars::service::app__backend_avatar_delete,
            api::app::backend_avatars::service::app__backend_avatar_file_get,
            api::app::backend_avatars::service::app__backend_avatar_gallery_get,
            api::app::backend_avatars::service::app__backend_avatar_get,
            api::app::backend_avatars::service::app__backend_avatar_impostor_create,
            api::app::backend_avatars::service::app__backend_avatar_impostor_delete,
            api::app::backend_avatars::service::app__backend_avatar_list_by_user_get,
            api::app::backend_avatars::service::app__backend_avatar_moderation_delete,
            api::app::backend_avatars::service::app__backend_avatar_moderations_get,
            api::app::backend_avatars::service::app__backend_avatar_moderation_send,
            api::app::backend_avatars::service::app__backend_avatar_save,
            api::app::backend_avatars::service::app__backend_avatar_select,
            api::app::backend_avatars::service::app__backend_avatar_select_fallback,
            api::app::backend_avatars::service::app__backend_avatar_styles_get,
            api::app::backend_favorites::service::app__backend_favorite_add,
            api::app::backend_favorites::service::app__backend_favorite_avatars_get,
            api::app::backend_favorites::service::app__backend_favorite_delete,
            api::app::backend_favorites::service::app__backend_favorite_groups_get,
            api::app::backend_favorites::service::app__backend_favorite_group_clear,
            api::app::backend_favorites::service::app__backend_favorite_group_save,
            api::app::backend_favorites::service::app__backend_favorite_limits_get,
            api::app::backend_favorites::service::app__backend_favorite_worlds_get,
            api::app::backend_favorites::service::app__backend_favorites_get,
            api::app::backend_favorites::service::app__backend_local_favorite_add,
            api::app::backend_favorites::service::app__backend_local_favorite_group_create,
            api::app::backend_favorites::service::app__backend_local_favorite_group_delete,
            api::app::backend_favorites::service::app__backend_local_favorite_group_rename,
            api::app::backend_favorites::service::app__backend_local_favorite_remove,
            api::app::backend_friends::service::app__backend_friend_status_get,
            api::app::backend_friends::service::app__backend_friend_delete,
            api::app::backend_friends::service::app__backend_friend_request_cancel,
            api::app::backend_friends::service::app__backend_friend_request_send,
            api::app::backend_friends::service::app__backend_friends_get,
            api::app::backend_groups::service::app__backend_group_audit_log_types_get,
            api::app::backend_groups::service::app__backend_group_bans_get,
            api::app::backend_groups::service::app__backend_group_block,
            api::app::backend_groups::service::app__backend_group_gallery_get,
            api::app::backend_groups::service::app__backend_group_get,
            api::app::backend_groups::service::app__backend_group_instances_get,
            api::app::backend_groups::service::app__backend_group_invite_delete,
            api::app::backend_groups::service::app__backend_group_invite_send,
            api::app::backend_groups::service::app__backend_group_invites_get,
            api::app::backend_groups::service::app__backend_group_join,
            api::app::backend_groups::service::app__backend_group_join_requests_get,
            api::app::backend_groups::service::app__backend_group_join_request_respond,
            api::app::backend_groups::service::app__backend_group_leave,
            api::app::backend_groups::service::app__backend_group_logs_get,
            api::app::backend_groups::service::app__backend_group_member_ban,
            api::app::backend_groups::service::app__backend_group_member_kick,
            api::app::backend_groups::service::app__backend_group_member_props_set,
            api::app::backend_groups::service::app__backend_group_member_unban,
            api::app::backend_groups::service::app__backend_group_members_get,
            api::app::backend_groups::service::app__backend_group_members_search,
            api::app::backend_groups::service::app__backend_group_post_create,
            api::app::backend_groups::service::app__backend_group_post_delete,
            api::app::backend_groups::service::app__backend_group_post_edit,
            api::app::backend_groups::service::app__backend_group_posts_get,
            api::app::backend_groups::service::app__backend_group_representation_set,
            api::app::backend_groups::service::app__backend_group_request_cancel,
            api::app::backend_groups::service::app__backend_group_unblock,
            api::app::backend_groups::service::app__backend_group_user_groups_get,
            api::app::backend_groups::service::app__backend_group_user_instances_get,
            api::app::backend_instances::service::app__backend_instance_close,
            api::app::backend_instances::service::app__backend_instance_create,
            api::app::backend_instances::service::app__backend_instance_get,
            api::app::backend_instances::service::app__backend_instance_self_invite,
            api::app::backend_instances::service::app__backend_instance_short_name_get,
            api::app::backend_media_api::service::app__backend_media_avatar_gallery_image_upload,
            api::app::backend_media_api::service::app__backend_media_avatar_image_set,
            api::app::backend_media_api::service::app__backend_media_avatar_image_upload_legacy,
            api::app::backend_media_api::service::app__backend_media_emoji_upload,
            api::app::backend_media_api::service::app__backend_media_file_delete,
            api::app::backend_media_api::service::app__backend_media_file_put,
            api::app::backend_media_api::service::app__backend_media_file_upload_finish,
            api::app::backend_media_api::service::app__backend_media_file_upload_start,
            api::app::backend_media_api::service::app__backend_media_file_version_create,
            api::app::backend_media_api::service::app__backend_media_files_get,
            api::app::backend_media_api::service::app__backend_media_gallery_image_upload,
            api::app::backend_media_api::service::app__backend_media_inventory_bundle_consume,
            api::app::backend_media_api::service::app__backend_media_inventory_item_update,
            api::app::backend_media_api::service::app__backend_media_inventory_items_get,
            api::app::backend_media_api::service::app__backend_media_print_delete,
            api::app::backend_media_api::service::app__backend_media_print_get,
            api::app::backend_media_api::service::app__backend_media_print_upload,
            api::app::backend_media_api::service::app__backend_media_prints_get,
            api::app::backend_media_api::service::app__backend_media_reward_redeem,
            api::app::backend_media_api::service::app__backend_media_sticker_upload,
            api::app::backend_media_api::service::app__backend_media_user_inventory_item_get,
            api::app::backend_media_api::service::app__backend_media_vrc_plus_icon_upload,
            api::app::backend_media_api::service::app__backend_media_world_image_set,
            api::app::backend_media_api::service::app__backend_media_world_image_upload_legacy,
            api::app::backend_moderation::app__backend_moderation_refresh,
            api::app::backend_moderation::app__backend_moderation_update,
            api::app::backend_notifications::service::app__backend_boop_send,
            api::app::backend_notifications::service::app__backend_invite_response_photo_send,
            api::app::backend_notifications::service::app__backend_invite_response_send,
            api::app::backend_notifications::service::app__backend_invite_send,
            api::app::backend_notifications::service::app__backend_notification_accept_friend_request,
            api::app::backend_notifications::service::app__backend_notification_hide_remote,
            api::app::backend_notifications::service::app__backend_notification_mark_seen,
            api::app::backend_notifications::service::app__backend_notification_respond,
            api::app::backend_notifications::service::app__backend_request_invite_send,
            api::app::backend_search::service::app__backend_search_config_get,
            api::app::backend_search::service::app__backend_search_groups_get,
            api::app::backend_search::service::app__backend_search_groups_strict_get,
            api::app::backend_search::service::app__backend_search_instance_short_name_get,
            api::app::backend_search::service::app__backend_search_users_get,
            api::app::backend_search::service::app__backend_search_worlds_get,
            api::app::backend_social::service::app__backend_favorites_baseline_get,
            api::app::backend_social::service::app__backend_friend_roster_baseline_get,
            api::app::backend_tools::service::app__backend_tools_calendars_get,
            api::app::backend_tools::service::app__backend_tools_featured_calendars_get,
            api::app::backend_tools::service::app__backend_tools_following_calendars_get,
            api::app::backend_tools::service::app__backend_tools_group_calendar_get,
            api::app::backend_tools::service::app__backend_tools_group_calendar_ics_get,
            api::app::backend_tools::service::app__backend_tools_group_event_follow,
            api::app::backend_tools::service::app__backend_tools_invite_message_edit,
            api::app::backend_tools::service::app__backend_tools_invite_messages_get,
            api::app::backend_tools::service::app__backend_tools_user_note_save,
            api::app::backend_tools::service::app__backend_tools_user_report,
            api::app::backend_users::service::app__backend_current_user_badge_update,
            api::app::backend_users::service::app__backend_current_user_tags_add,
            api::app::backend_users::service::app__backend_current_user_tags_remove,
            api::app::backend_users::service::app__backend_current_user_update,
            api::app::backend_users::service::app__backend_user_get,
            api::app::backend_users::service::app__backend_user_groups_get,
            api::app::backend_users::service::app__backend_user_mutual_counts_get,
            api::app::backend_users::service::app__backend_user_mutual_friends_get,
            api::app::backend_users::service::app__backend_user_represented_group_get,
            api::app::backend_worlds::service::app__backend_world_delete,
            api::app::backend_worlds::service::app__backend_world_get,
            api::app::backend_worlds::service::app__backend_world_list_by_user_get,
            api::app::backend_worlds::service::app__backend_world_persistent_data_delete,
            api::app::backend_worlds::service::app__backend_world_persistent_data_exists,
            api::app::backend_worlds::service::app__backend_world_publish,
            api::app::backend_worlds::service::app__backend_world_save,
            api::app::backend_worlds::service::app__backend_world_unpublish,
            api::app::window::app__set_user_agent,
            api::app::shell::app__open_link,
            api::app::shell::app__open_discord_profile,
            api::discord::discord__set_active,
            api::discord::discord__set_assets,
            api::app::shell::app__get_file_base64,
            api::app::shell::app__get_file_bytes,
            api::app::shell::app__read_config_file,
            api::app::shell::app__read_config_file_safe,
            api::app::shell::app__write_config_file,
            api::app::paths::app__get_vrchat_app_data_location,
            api::app::paths::app__get_vrchat_photos_location,
            api::app::paths::app__get_ugc_photo_location,
            api::app::paths::app__get_vrchat_cache_location,
            api::app::paths::app__get_vrchat_screenshots_location,
            api::app::shell::app__open_vrcx_app_data_folder,
            api::app::shell::app__open_vrc_app_data_folder,
            api::app::shell::app__open_vrc_photos_folder,
            api::app::shell::app__open_ugc_photos_folder,
            api::app::shell::app__open_vrc_screenshots_folder,
            api::app::shell::app__open_crash_vrc_crash_dumps,
            api::app::shell::app__open_shortcut_folder,
            api::app::shell::app__open_folder_and_select_item,
            api::app::shell::app__open_file_selector_dialog,
            api::app::shell::app__open_folder_selector_dialog,
            api::app::shell::app__save_vrc_reg_json_file,
            api::app::window::app__focus_window,
            api::app::window::app__flash_window,
            api::app::window::app__change_theme,
            api::app::window::app__do_funny,
            api::app::window::app__set_tray_icon_notification,
            api::app::window::app__restart_application,
            api::app::window::app__exit_application,
            api::app::updater::app__check_tauri_update,
            api::app::updater::app__download_and_install_tauri_update,
            api::app::legacy_migration::app__check_legacy_vrcx_available,
            api::app::legacy_migration::app__get_legacy_vrcx_force_migration_status,
            api::app::legacy_migration::app__get_legacy_vrcx_migration_status,
            api::app::legacy_migration::app__request_legacy_migration,
            api::app::legacy_migration::app__request_legacy_vrcx_force_migration,
            api::app::clipboard::app__get_clipboard,
            api::app::clipboard::app__copy_image_to_clipboard,
            api::app::window::app__set_startup,
            api::app::registry::app__get_vrchat_registry_key,
            api::app::registry::app__get_vrchat_registry_key_string,
            api::app::registry::app__has_vrchat_registry_folder,
            api::app::registry::app__delete_vrchat_registry_folder,
            api::app::registry::app__set_vrchat_registry_key,
            api::app::registry::app__get_vrchat_registry,
            api::app::registry::app__set_vrchat_registry,
            api::app::registry::app__read_vrc_reg_json_file,
            api::app::window::app__desktop_notification,
            api::app::local_player_moderations::app__get_vrchat_moderations,
            api::app::local_player_moderations::app__get_vrchat_user_moderation,
            api::app::local_player_moderations::app__set_vrchat_user_moderation,
            api::app::ipc_commands::app__ipc_announce_start,
            api::app::ipc_commands::app__send_ipc,
            api::app::ipc_commands::app__set_app_launcher_settings,
            api::app::ipc_commands::app__try_open_instance_in_vrc,
            api::app::calendar::app__open_calendar_file,
            api::app::calendar::app__save_calendar_file,
            api::app::media::app__save_image_file,
            api::app::media::app__get_image,
            api::app::media::app__resize_image_to_fit_limits,
            api::app::media::app__sign_file,
            api::app::screenshots::app__get_extra_screenshot_data,
            api::app::screenshots::app__get_screenshot_metadata,
            api::app::screenshots::app__find_screenshots_by_search,
            api::app::screenshots::app__start_screenshot_library_scan,
            api::app::screenshots::app__get_screenshot_library_status,
            api::app::screenshots::app__get_screenshot_folder_tree,
            api::app::screenshots::app__get_screenshot_folder_images,
            api::app::screenshots::app__get_world_screenshots,
            api::app::screenshots::app__ensure_screenshot_thumbnail,
            api::app::screenshots::app__get_last_screenshot,
            api::app::screenshots::app__delete_screenshot_metadata,
            api::app::screenshots::app__delete_all_screenshot_metadata,
            api::app::screenshots::app__add_screenshot_metadata,
            api::app::media::app__crop_all_prints,
            api::app::media::app__crop_print_image,
            api::app::media::app__save_print_to_file,
            api::app::media::app__save_sticker_to_file,
            api::app::media::app__save_emoji_to_file,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
